(ns chip8-clj.test-DXYN
  (:require [chip8-clj.graphics :as graphics]
            [chip8-clj.machine-state :as machine-state])
  (:require [clojure.test :refer :all]
            [chip8-clj.core :refer :all]))

(deftest draw-sprite-test
  (let [pre-machine-state (-> (machine-state/initialise)
                              (machine-state/set-pc 0)
                              (machine-state/set-instr 0 0xD122)
                              (machine-state/set-addr-reg 2)
                              (machine-state/set-memory 2 0x55)
                              (machine-state/set-memory 3 0xaa)
                              (machine-state/set-register 1 0)
                              (machine-state/set-register 2 0)
                              (machine-state/set-screen-buffer 0 0 1)
                              (machine-state/set-screen-buffer 1 0 0)
                              (machine-state/set-screen-buffer 2 0 1)
                              (machine-state/set-screen-buffer 3 0 0)
                              (machine-state/set-screen-buffer 4 0 1)
                              (machine-state/set-screen-buffer 5 0 0)
                              (machine-state/set-screen-buffer 6 0 1)
                              (machine-state/set-screen-buffer 7 0 0)
                              (machine-state/set-screen-buffer 0 1 0)
                              (machine-state/set-screen-buffer 1 1 1)
                              (machine-state/set-screen-buffer 2 1 0)
                              (machine-state/set-screen-buffer 3 1 1)
                              (machine-state/set-screen-buffer 4 1 0)
                              (machine-state/set-screen-buffer 5 1 1)
                              (machine-state/set-screen-buffer 6 1 0)
                              (machine-state/set-screen-buffer 7 1 1))
        post-machine-state (step pre-machine-state)]

    ; Checks the screen buffer has been updated.
    (is (= (machine-state/get-screen-buffer post-machine-state 0 0) 1))
    (is (= (machine-state/get-screen-buffer post-machine-state 1 0) 1))
    (is (= (machine-state/get-screen-buffer post-machine-state 2 0) 1))
    (is (= (machine-state/get-screen-buffer post-machine-state 3 0) 1))
    (is (= (machine-state/get-screen-buffer post-machine-state 4 0) 1))
    (is (= (machine-state/get-screen-buffer post-machine-state 5 0) 1))
    (is (= (machine-state/get-screen-buffer post-machine-state 6 0) 1))
    (is (= (machine-state/get-screen-buffer post-machine-state 7 0) 1))
    (is (= (machine-state/get-screen-buffer post-machine-state 0 1) 1))
    (is (= (machine-state/get-screen-buffer post-machine-state 1 1) 1))
    (is (= (machine-state/get-screen-buffer post-machine-state 2 1) 1))
    (is (= (machine-state/get-screen-buffer post-machine-state 3 1) 1))
    (is (= (machine-state/get-screen-buffer post-machine-state 4 1) 1))
    (is (= (machine-state/get-screen-buffer post-machine-state 5 1) 1))
    (is (= (machine-state/get-screen-buffer post-machine-state 6 1) 1))
    (is (= (machine-state/get-screen-buffer post-machine-state 7 1) 1))
    ; Checks that VF (the carry flag) is not set.
    (is (= (machine-state/get-register post-machine-state 0xF) 0))
    ; Checks that the pc has been updated correctly.
    (is (= (machine-state/get-pc post-machine-state) 2))))

(deftest draw-sprite-with-carry-test
  (let [pre-machine-state (-> (machine-state/initialise)
                              (machine-state/set-pc 0)
                              (machine-state/set-instr 0 0xD122)
                              (machine-state/set-addr-reg 2)
                              (machine-state/set-memory 2 0x55)
                              (machine-state/set-memory 3 0xaa)
                              (machine-state/set-register 1 0)
                              (machine-state/set-register 2 0)
                              (machine-state/set-screen-buffer 0 0 0)
                              (machine-state/set-screen-buffer 1 0 1)
                              (machine-state/set-screen-buffer 2 0 0)
                              (machine-state/set-screen-buffer 3 0 1)
                              (machine-state/set-screen-buffer 4 0 0)
                              (machine-state/set-screen-buffer 5 0 1)
                              (machine-state/set-screen-buffer 6 0 0)
                              (machine-state/set-screen-buffer 7 0 1)
                              (machine-state/set-screen-buffer 0 1 1)
                              (machine-state/set-screen-buffer 1 1 0)
                              (machine-state/set-screen-buffer 2 1 1)
                              (machine-state/set-screen-buffer 3 1 0)
                              (machine-state/set-screen-buffer 4 1 1)
                              (machine-state/set-screen-buffer 5 1 0)
                              (machine-state/set-screen-buffer 6 1 1)
                              (machine-state/set-screen-buffer 7 1 0))
        post-machine-state (step pre-machine-state)]

    ; Checks the screen buffer has been updated.
    (is (= (machine-state/get-screen-buffer post-machine-state 0 0) 0))
    (is (= (machine-state/get-screen-buffer post-machine-state 1 0) 0))
    (is (= (machine-state/get-screen-buffer post-machine-state 2 0) 0))
    (is (= (machine-state/get-screen-buffer post-machine-state 3 0) 0))
    (is (= (machine-state/get-screen-buffer post-machine-state 4 0) 0))
    (is (= (machine-state/get-screen-buffer post-machine-state 5 0) 0))
    (is (= (machine-state/get-screen-buffer post-machine-state 6 0) 0))
    (is (= (machine-state/get-screen-buffer post-machine-state 7 0) 0))
    (is (= (machine-state/get-screen-buffer post-machine-state 0 1) 0))
    (is (= (machine-state/get-screen-buffer post-machine-state 1 1) 0))
    (is (= (machine-state/get-screen-buffer post-machine-state 2 1) 0))
    (is (= (machine-state/get-screen-buffer post-machine-state 3 1) 0))
    (is (= (machine-state/get-screen-buffer post-machine-state 4 1) 0))
    (is (= (machine-state/get-screen-buffer post-machine-state 5 1) 0))
    (is (= (machine-state/get-screen-buffer post-machine-state 6 1) 0))
    (is (= (machine-state/get-screen-buffer post-machine-state 7 1) 0))
    ; Checks that VF (the carry flag) is set.
    (is (= (machine-state/get-register post-machine-state 0xF) 1))
    ; Checks that the pc has been updated correctly.
    (is (= (machine-state/get-pc post-machine-state) 2))))



